spring.application.name=sfdc

# Salesforce Configuration
# Use environment variables for sensitive data to keep the repository public-safe
salesforce.login-url=https://axaid-ccc--sbrlsdmtm.sandbox.my.salesforce.com
salesforce.client-id=${client_id}
salesforce.client-secret=${client_secret}
salesforce.grant-type=client_credentials
salesforce.api-version=v61.0
