spring.application.name=sfdc

# Salesforce Configuration
salesforce.login-url=https://login.salesforce.com
salesforce.client-id=YOUR_CLIENT_ID
salesforce.client-secret=YOUR_CLIENT_SECRET
salesforce.username=YOUR_USERNAME
salesforce.password=YOUR_PASSWORD_AND_SECURITY_TOKEN
salesforce.api-version=v60.0

